### ISSUE TITLE
isSuccess not succeeding at all

### ISSUE THREAD

**Issue by RussianRonin** [ForceComDeveloper/Apex_reCaptcha#1]
I am trying to run this on a page and it is not succeeding no matter what i do.

**Comment by scolladon** [comment]
Have you configured the custom settings ?

**Comment by srujan21** [comment]
I have configured custom settings and tried to use like this and I see empty page. 

`<apex:page >`
    `<apex:form rendered="true">`
    	 `<c:reCaptcha/>`
   ` </apex:form>`
`</apex:page> `

**Comment by scolladon** [comment]
Have you inspired yourself using the test ?

**Comment by srujan21** [comment]
Yeah the test runs fine, I have forgot to remove `layout="none"` from `<apex:outpanel>` in component. Now the result is being **not verified**.  Here is my class 
![recapt](https://cloud.githubusercontent.com/assets/11474139/20558406/d6410504-b195-11e6-843c-9f4b5e0cf25e.PNG)

**Comment by scolladon** [comment]
Do the api keys are correct ?

**Comment by srujan21** [comment]
Yeah I copied them directly from reCAPTCHA admin.

**Comment by scolladon** [comment]
Can you show the verify code you are doing ?

**Comment by srujan21** [comment]
Here is the code snippet 
![recaptch](https://cloud.githubusercontent.com/assets/11474139/20558619/f7b7adfe-b196-11e6-8554-58b470e8ecd8.PNG)

**Comment by scolladon** [comment]
How is configure the custom settings ?

**Comment by srujan21** [comment]
Yeah I have verified again and they are correct.

**Comment by scolladon** [comment]
Is there a header 'X-Salesforce-SIP' when you call verify ?

**Comment by srujan21** [comment]
I am not setting any headers.  Do you want me to set that header on page ?

**Comment by scolladon** [comment]
Can you system.debug(ApexPages.currentPage().getHeaders()) and see the result ?

**Comment by srujan21** [comment]
yes,
17:32:47:805 USER_DEBUG [5]|DEBUG|{Accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8, Accept-Encoding=gzip, deflate, sdch, br, Accept-Language=en-US,en;q=0.8, CipherSuite=ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 256-bits, Connection=keep-alive, DNT=1, Host=srpkg.ap2.visual.force.com, Referer=https://ap2.salesforce.com/_ui/common/apex/debug/ApexCSIPage, Upgrade-Insecure-Requests=1, User-Agent=Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36, ...}

**Comment by scolladon** [comment]
Is there a header X-Salesforce-SIP or x-original-remote-addr ?
Is it possible to debug it ?
System.Debug(ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP'));
System.Debug(ApexPages.currentPage().getHeaders().get('x-original-remote-addr'));

**Comment by srujan21** [comment]
'X-Salesforce-SIP - 203.109.111.100 
x-original-remote-addr' - null

**Comment by scolladon** [comment]
is it possible to replace the method verify with the following code : 
public static Boolean verify(final String response, final Map<String, String> hdrs) {
    Boolean verif = false;
    final HttpResponse res = makeRequest(
      'secret=' + recaptchaConfig.secretKey__c +
      '&response='  + response +
      '&remoteip='  + reCaptcha.remoteHost(hdrs)
    );
    System.Debug(reCaptcha.remoteHost(hdrs));
    System.Debug(res);
    System.Debug(res.getBody());
    if (res != null) {
      if ( res.getStatusCode() == 200 ) {
        final System.JSONParser parser = System.JSON.createParser(res.getBody());
        while (parser.nextToken() != null) {
          if ((parser.getCurrentToken() == JSONToken.FIELD_NAME) && (parser.getText() == 'success')) {
            parser.nextToken();
            verif = parser.getText() == 'true';
            break;
          }
        }
      }
    }
    return verif;
  }

and share the debug log

**Comment by srujan21** [comment]
okay

**Comment by srujan21** [comment]
user debug
![recaptcha debug](https://cloud.githubusercontent.com/assets/11474139/20561662/aba1ed58-b1a5-11e6-85cb-22c569879bac.PNG)

**Comment by scolladon** [comment]
Could you add
System.Debug(response); also in the method ?

**Comment by srujan21** [comment]
oops the response itself is null 
![recaptcha debug 2](https://cloud.githubusercontent.com/assets/11474139/20562188/5d97bfc2-b1a8-11e6-9f5d-08d1567a3571.PNG)

**Comment by srujan21** [comment]
I have modified component because the original code isn't showing recaptcha, i mean its showing for the first time and if i reload then i am getting empty page. but i think this change  wouldn't  be the  problem.
![component](https://cloud.githubusercontent.com/assets/11474139/20562295/d71d58ac-b1a8-11e6-8d9c-5f197ed9bdd5.PNG)

**Comment by scolladon** [comment]
I think it misses ?onload=loadCaptcha&render=explicit

At the end of the first script src.
Try to put the the second script block before the first one also

**Comment by scolladon** [comment]
Show me the page and the ctrl too please.
I do not see the action which send the form to the controller

**Comment by srujan21** [comment]
did changes as you said
my page
![page](https://cloud.githubusercontent.com/assets/11474139/20562700/ff1dada0-b1aa-11e6-87b8-a25b6517d7d9.PNG)
my class 
![class](https://cloud.githubusercontent.com/assets/11474139/20562704/04271a5c-b1ab-11e6-9edb-93fc7f73d713.PNG)

**Comment by srujan21** [comment]
and recaptcha is not being loaded if i add `?onload=loadCaptcha&render=explicit`

**Comment by scolladon** [comment]
How do you submit the form ?
The recaptcha library is used only in the submit form code.
I do not see how the form is submit and so how your recapt function is called from the view...

**Comment by srujan21** [comment]
I am just checking debugs , I think the `g-recaptcha-response` is important.  and I am doing verification in controller itself.

**Comment by srujan21** [comment]
Yeah I am sorry my mistake. Now validated. Thanks. 💯

**Comment by scolladon** [comment]
Cool. Thanks
